// Mocks generated by Mockito 5.4.6 from annotations
// in intelliresume/test/data/repositories/resume_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:intelliresume/data/datasources/local/resume_local_ds.dart'
    as _i2;
import 'package:intelliresume/data/datasources/remote/remote_resume_ds.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [LocalResumeDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalResumeDataSource extends _i1.Mock
    implements _i2.LocalResumeDataSource {
  MockLocalResumeDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> cacheResume(String? userId, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#cacheResume, [userId, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> getCachedResume(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedResume, [userId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);
}

/// A class which mocks [RemoteResumeDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteResumeDataSource extends _i1.Mock
    implements _i4.RemoteResumeDataSource {
  MockRemoteResumeDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> saveResume(String? userId, Map<String, dynamic>? data) =>
      (super.noSuchMethod(
            Invocation.method(#saveResume, [userId, data]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>?> fetchResume(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchResume, [userId]),
            returnValue: _i3.Future<Map<String, dynamic>?>.value(),
          )
          as _i3.Future<Map<String, dynamic>?>);
}
