// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABWadBd1qz1CzwFjmF17j1rZfxldntE_g',
    appId: '1:260299601243:web:097612903c2afbcc68d67e',
    messagingSenderId: '260299601243',
    projectId: 'resume-flutte-pwa',
    authDomain: 'resume-flutte-pwa.firebaseapp.com',
    storageBucket: 'resume-flutte-pwa.firebasestorage.app',
    measurementId: 'G-X96W7QYQ05',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT7GlMXkY9xK9Gw3YAGdqKzU9BUPVPr8U',
    appId: '1:260299601243:android:e5792c653fd7858f68d67e',
    messagingSenderId: '260299601243',
    projectId: 'resume-flutte-pwa',
    storageBucket: 'resume-flutte-pwa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCor_ZDVP9UfLJp28Et5bLo5EaxZ9ovqYg',
    appId: '1:260299601243:ios:c8ba23a3b29e6b5f68d67e',
    messagingSenderId: '260299601243',
    projectId: 'resume-flutte-pwa',
    storageBucket: 'resume-flutte-pwa.firebasestorage.app',
    iosClientId:
        '260299601243-5mfp6ufgbumhee9bglcmjh6qrrlbmrdn.apps.googleusercontent.com',
    iosBundleId: 'com.example.intelliresume',
  );
}
