// Mocks generated by Mockito 5.4.6 from annotations
// in intelliresume/test/domain/usecases/update_plan_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:intelliresume/data/repositories/user_profile_repository.dart'
    as _i2;
import 'package:intelliresume/domain/entities/user_profile.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [UserProfileRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileRepository extends _i1.Mock
    implements _i2.UserProfileRepository {
  MockUserProfileRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.UserProfile?> loadProfile(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#loadProfile, [uid]),
            returnValue: _i3.Future<_i4.UserProfile?>.value(),
          )
          as _i3.Future<_i4.UserProfile?>);

  @override
  _i3.Future<void> saveProfile(_i4.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#saveProfile, [profile]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> deleteProfile(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProfile, [uid]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> verifyProfileEmail() =>
      (super.noSuchMethod(
            Invocation.method(#verifyProfileEmail, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> updateProfile(_i4.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [profile]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Stream<_i4.UserProfile> watchProfile(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#watchProfile, [uid]),
            returnValue: _i3.Stream<_i4.UserProfile>.empty(),
          )
          as _i3.Stream<_i4.UserProfile>);

  @override
  _i3.Future<_i4.UserProfile?> getCachedProfile(String? uid) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedProfile, [uid]),
            returnValue: _i3.Future<_i4.UserProfile?>.value(),
          )
          as _i3.Future<_i4.UserProfile?>);
}
